### ISSUE TITLE
Redis error on new project start

### ISSUE THREAD

**Issue by kristjankoppel** [kalabox/lando#107]
With home router and internet connection i managed to get error like this:
`error:  Error: Ready check failed: Redis connection lost and command aborted in uncertain state. It might have been processed.
    at RedisClient.connection_gone (/thebox/Users/travis/build/kalabox/lando/build/cli/node_modules/redis/index.js:559:17)
    at Socket.<anonymous> (/thebox/Users/travis/build/kalabox/lando/build/cli/node_modules/redis/index.js:164:14)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

And lando throw that error repeatetly and exited. When i ran "lando start" straight again lando started fine. Error was only with initial start.

I'm running lando on macos sierra 10.12.3 with lando v3.0.0-alpha.5 . I have new computer so it's pretty clean. Don't really know what ports to check also.

**Comment by robertgarrigos** [comment]
I'm having the same issue with Sierra 10.12.5 and lando v3.0.0-alpha.13 but slightly different error message:

```
error:  Error: Ready check failed: Redis connection lost and command aborted in uncertain state. It might have been processed.
    at RedisClient.connection_gone (/snapshot/cli/node_modules/redis/index.js:559:17)
    at Socket.<anonymous> (/snapshot/cli/node_modules/redis/index.js:164:14)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Actually, this message got printed 4 times on terminal

**Comment by pirog** [comment]
@kristjankoppel @robertgarrigos this should be resolved in alpha.14+, removed hipache as the proxy in favor of traefik
