### ISSUE TITLE
the input device is not a TTY

### ISSUE THREAD

**Issue by RistoNiinemets** [kalabox/lando#265]
Bug Report
==========

**Tell us about your setup**
What is your lando version and operating system?

Windows 10 professional
v3.0.0-beta7 (also alpha.19 did that)

**Tell us about your `.lando.yml`**
```yml
name: mywebsite
recipe: wordpress
services:
  pma:
    type: phpmyadmin
  mail:
    type: mailhog
```

**Tell us about the command you were running**

At first, I did not change anything, only updated Lando and then rebuilt for no reason. Also tried to change the config - added phpmyadmin and mailhog.

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

*Example:*

```bash
? Are you sure you want to rebuild? Yes
Removing mywebsite_mail_1 ... done
Removing mywebsite_pma_1 ... done
Removing mywebsite_database_1 ... done
Removing mywebsite_appserver_1 ... done
Pulling appserver (kalabox/php:7.1-apache)...
Pulling mail (mailhog/mailhog:latest)...
Pulling pma (phpmyadmin/phpmyadmin:latest)...
Pulling database (mysql:latest)...
appserver uses an image, skipping
mail uses an image, skipping
pma uses an image, skipping
database uses an image, skipping
Recreating lando_proxy_1 ...
Recreating lando_proxy_1 ... done
Creating mywebsite_appserver_1 ...
Creating mywebsite_database_1 ...
Creating mywebsite_pma_1 ...
Creating mywebsite_mail_1 ...
Creating mywebsite_pma_1
Creating mywebsite_appserver_1
Creating mywebsite_mail_1
Creating mywebsite_database_1 ... done
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
error:  Error: 1
    at ChildProcess.<anonymous> (C:\snapshot\cli\lib\shell.js:143:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at spawn (C:\snapshot\cli\lib\shell.js:93:10)
    at Object.exports.sh (C:\snapshot\cli\lib\shell.js:209:12)
    at shCompose (C:\snapshot\cli\lib\compose.js:24:16)
    at Object.exports.run (C:\snapshot\cli\lib\compose.js:343:10)
    at C:\snapshot\cli\lib\docker.js:161:22
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\docker.js:148:18)
    at C:\snapshot\cli\lib\engine.js:526:19
    at runCallback (timers.js:800:20)
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\engine.js:525:4)
    at AsyncEvents.<anonymous> (C:\snapshot\cli\plugins\lando-services\lib\config.js:148:31)
    at AsyncEvents.handle (C:\snapshot\cli\lib\events.js:109:19)
    at C:\snapshot\cli\lib\events.js:170:19
From previous event:
    at AsyncEvents.emit (C:\snapshot\cli\lib\events.js:161:18)
    at C:\snapshot\cli\lib\app.js:757:23
From previous event:
    at Object.exports.start (C:\snapshot\cli\lib\app.js:756:4)
    at C:\snapshot\cli\lib\app.js:1037:17
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.rebuild (C:\snapshot\cli\lib\app.js:1036:4)
    at C:\snapshot\cli\plugins\lando-core\lib\tasks\rebuild.js:56:28
From previous event:
    at Object.run (C:\snapshot\cli\plugins\lando-core\lib\tasks\rebuild.js:48:8)
    at C:\snapshot\cli\lib\tasks.js:137:19
    at <anonymous>

```

Appserver boots up and site works. Mailhog and PhpMyAdmin services seem to be booting up, but in my test, Mailhog is not catching any emails.

**Comment by pirog** [comment]
@RistoNiinemets what shell are you running these commands from?

**Comment by RistoNiinemets** [comment]
@pirog Git Bash

**Comment by RistoNiinemets** [comment]
@pirog Well, it seems to be the problem. I now tried with built-in Command Prompt and no errors. It sure did work before on two different machines. Way too simple mistake :( Thanks for the quick response.

**Comment by pirog** [comment]
@RistoNiinemets unfortunately i think node (which is what the CLI is built with) does not play nice with any "pseudo terminals" eg anything that is based in ming or cywgin (which i think git bash is based on). 

It might be worthwhile reopening (and renaming) this issue so we can clarify that restriction in our documentation

**Comment by stevenkkim** [comment]
@RistoNiinemets, I was getting the same error in Git Bash on Windows 10 when running the "lando start" command. I found that prefixing the command with winpty solved my problem (command: "winpty lando start"), maybe this will help you out. This was the [article](http://willi.am/blog/2016/08/08/docker-for-windows-interactive-sessions-in-mintty-git-bash/) that cued me in to the solution.

@pirog, I saw you updated the documentation that Windows users must use cmd or powershell -- I'm not technical enough to know whether winpty is the right answer, but if it is, then maybe you could add it to the documentation since many Windows users prefer the Git Bash to cmd/powershell.
